// Login
export const CHANGE_LOGIN_USERNAME = 'CHANGE_LOGIN_USERNAME'
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD'
export const ERROR_IN_USER_LOGIN = 'ERROR_IN_USER_LOGIN'
export const RESTORE_LOGIN_ERROR = 'RESTORE_LOGIN_ERROR'
export const RESEND_CONFIRMATION_EMAIL_FORM_MESSAGE_HANDLER = 'RESEND_CONFIRMATION_EMAIL_FORM_MESSAGE_HANDLER'
export const CHANGE_LOGIN_EMAIL = 'CHANGE_LOGIN_EMAIL'

// Register
export const CHANGE_REGISTER_USERNAME = 'CHANGE_REGISTER_USERNAME'
export const CHANGE_REGISTER_PASSWORD = 'CHANGE_REGISTER_PASSWORD'
export const CHANGE_NAME = 'CHANGE_NAME'
export const CHANGE_LASTNAME = 'CHANGE_LASTNAME'
export const CHANGE_BIRTHDAY = 'CHANGE_BIRTHDAY'
export const CHANGE_EMAIL = 'CHANGE_EMAIL'
export const ERROR_IN_NEW_USER = 'ERROR_IN_NEW_USER'
export const RESTORE_REGISTER_ERROR = 'RESTORE_REGISTER_ERROR'
export const JUST_REGISTERED_HANDLER = 'JUST_REGISTERED_HANDLER'

// General

export const CHANGE_DRAWER_OPEN_STATUS = 'CHANGE_DRAWER_OPEN_STATUS'
export const CHANGE_HAS_SESSION_STATUS = 'CHANGE_HAS_SESSION_STATUS'
